version: 0.0
os: linux
files:
    - source: *.rpm
      destination: /home/ec2-user
permissions:
    - object: /home/ec2-user/*.rpm
      owner: ec2-user
      group: ec2-user
      mode: 755
      type:
        - file
hooks:
  BeforeInstall:
    - location: scripts/codedeploy/install-grafana.sh
      runas: root
